### ISSUE TITLE
can i search when enter 'mmh' , if i have too many servers

### ISSUE THREAD

**Issue by Teddy-Zhu** [mritd/mmh#3]

**Comment by mritd** [comment]
Search is not supported. 

Finding target servers through repeated keyboard searches is inefficient, and multiple profiles will be supported in the future to easily isolate different environment configurations. If possible, it might be a good idea to use bash/zsh completion.

The search ability of sshw comes from the terminal prompt library [promptui](https://github.com/manifoldco/promptui), and all the terminal prompt libraries in golang are lack of support for Chinese, such as the keyboard shortcut `ctrl+a`、`ctrl+e`; therefore I created a terminal prompt library [promptx](https://github.com/mritd/promptx), I have not Increase search capabilities because I think list search on the terminal is inefficient.

搜索功能目前并没有被支持，因为我感觉在终端上进行搜索动作很低效；为了弥补这个问题后续会增加多配置文件支持，方便隔离不同的环境配置；如果可能的话可以考虑增加 bash/zsh completion, 这样在终端上不断 tag 就可以了。

题外话，sshw 的搜索实际上是由终端提示库 [promptui](https://github.com/manifoldco/promptui) 提供的，在很久以前我就尝试了基本全部的主流终端提示库，不幸的是基本全部不支持中文(光标移动 bug、删除退格 bug 等等)；后来自己造了一个轮子 [promptx](https://github.com/mritd/promptx)，支持了中文同时又支持了常规的习惯性操作 `ctrl+a`、`ctrl+b` 等；不过我当时没有给这个提示库增加搜索能力，原因跟上文一样。

**Comment by Teddy-Zhu** [comment]
ok , thx
